### ISSUE TITLE
Lorenz attractor demo has no colormap applied

### ISSUE THREAD

**Issue by steffenhaug** [MakieOrg/Website#13]
I noticed the Lorenz-attractor demo on the website appears to have broken. It doesnt seem to have a colormap applied.

![Image](https://github.com/user-attachments/assets/e24681be-5511-41fb-8d65-51c6d833f4c4)

I'm pretty sure this changed since yesterday, because I had the tab open at work from yesterday. I guess there was some breaking change in yesterdays Makie update which affected it?

**Comment by SimonDanisch** [comment]
Fixed here: https://github.com/MakieOrg/Makie.jl/pull/4258
Btw, Website is the repository for https://makie.org/, so not related to the docs

**Comment by steffenhaug** [comment]
Oh duh, sorry about that, I didn't realize I was on `docs.makie.org`, and not `makie.org`, because I just got there by googling Makie... Thanks for letting me know! I'll close the issue.
